"""empty message

Revision ID: 5d06304e0f6e
Revises: 0627a3e4d6d8
Create Date: 2020-03-23 14:01:01.747305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d06304e0f6e'
down_revision = '0627a3e4d6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.execute('UPDATE shows SET start_time = start_date;')
    op.alter_column('shows', 'start_time', existing_type=sa.DateTime(), nullable=False)
    op.drop_column('shows', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.execute('UPDATE shows SET start_date = start_time;')
    op.alter_column('shows', 'start_date', existing_type=sa.DateTime(), nullable=False)
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
